FROM python:3.7

WORKDIR /app
ADD . /app

ADD https://s3.amazonaws.com/voxmedia-docker-utils/docker-ssh-exec docker-ssh-exec
RUN chmod +x docker-ssh-exec
RUN mkdir /root/.ssh
RUN ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
RUN ./docker-ssh-exec pip install -r requirements.txt

CMD ["./run.sh"]
